@echo off
echo Importing existing AWS resources into Terraform state...
echo.

echo [1/16] ECR api...
terraform import aws_ecr_repository.services["api"] market-sensemaking/api

echo [2/16] ECR collector...
terraform import aws_ecr_repository.services["collector"] market-sensemaking/collector

echo [3/16] ECR reactor...
terraform import aws_ecr_repository.services["reactor"] market-sensemaking/reactor

echo [4/16] ECR tile-worker...
terraform import aws_ecr_repository.services["tile-worker"] market-sensemaking/tile-worker

echo [5/16] CloudWatch api...
terraform import aws_cloudwatch_log_group.ecs["api"] /ecs/market-sensemaking/api

echo [6/16] CloudWatch collector...
terraform import aws_cloudwatch_log_group.ecs["collector"] /ecs/market-sensemaking/collector

echo [7/16] CloudWatch reactor...
terraform import aws_cloudwatch_log_group.ecs["reactor"] /ecs/market-sensemaking/reactor

echo [8/16] CloudWatch tile-worker...
terraform import aws_cloudwatch_log_group.ecs["tile-worker"] /ecs/market-sensemaking/tile-worker

echo [9/16] IAM ecs-task-execution...
terraform import aws_iam_role.ecs_task_execution market-sensemaking-ecs-task-execution-role

echo [10/16] IAM ecs-task...
terraform import aws_iam_role.ecs_task market-sensemaking-ecs-task-role

echo [11/16] IAM rds-monitoring...
terraform import aws_iam_role.rds_monitoring market-sensemaking-rds-monitoring-role

echo [12/16] DB subnet group...
terraform import aws_db_subnet_group.main market-sensemaking-db-subnet-group

echo [13/16] DB parameter group...
terraform import aws_db_parameter_group.postgres market-sensemaking-pg15-params

echo [14/16] ElastiCache subnet group...
terraform import aws_elasticache_subnet_group.main market-sensemaking-redis-subnet-group

echo [15/16] ElastiCache parameter group...
terraform import aws_elasticache_parameter_group.redis market-sensemaking-redis-params

echo [16/16] S3 bucket...
terraform import aws_s3_bucket.alb_logs market-sensemaking-alb-logs-821482074659

echo.
echo Import complete!
pause
